export const RUBROS = [
  "Gastronomía",
  "Cosmética",
  "Indumentaria",
  "Artesanías",
  "Velas y aromas",
  "Servicios",
  "Cafeterías",
  "Dulces y repostería",
  "Decoración",
  "Belleza",
  "Bazar y hogar",
  "Accesorios",
  "Fotografía",
  "Diseño",
  "E-commerce",
  "Tienda online",
  "Cursos y formación",
  "Consultoría",
  "Reparaciones",
  "Peluquería y estética",
  "Otro",
] as const;

export const DEFAULT_CATEGORY = "Otro";
